FROM ubuntu:rolling
ENV DEBIAN_FRONTEND=noninteractive

# Install ubuntu dependencies
RUN apt-get update -y && \
    apt-get install git jq bc make automake rsync htop curl build-essential pkg-config libffi-dev libgmp-dev libssl-dev libtinfo-dev libsystemd-dev zlib1g-dev make g++ wget libncursesw5 libtool autoconf -y

#Install libsodium
RUN cd ${HOME} && \
    git clone https://github.com/input-output-hk/libsodium && \
    cd libsodium && \
    git checkout 66f017f1 && \
    ./autogen.sh && \
    ./configure && \
    make && \
    make install

# Update PATH
ENV PATH="~/.local/bin:${PATH}"
ENV LD_LIBRARY_PATH="/usr/local/lib:$LD_LIBRARY_PATH"
ENV PKG_CONFIG_PATH="/usr/local/lib/pkgconfig:$PKG_CONFIG_PATH"

# Get latest config files from IOHK github api
RUN export URL_CONFIG_FILES=$(curl -s https://api.github.com/repos/input-output-hk/cardano-node/releases/latest | jq -r .body | grep 'Configuration files' | sed 's/\(- \[Configuration files\]\)//' | tr -d '()\r' | sed 's/\/index\.html//') && \
    echo $URL_CONFIG_FILES && \
    wget -P ${HOME}/node $URL_CONFIG_FILES/testnet-config.json && \
    wget -P ${HOME}/node $URL_CONFIG_FILES/testnet-byron-genesis.json && \
    wget -P ${HOME}/node $URL_CONFIG_FILES/testnet-shelley-genesis.json && \
    wget -P ${HOME}/node $URL_CONFIG_FILES/testnet-alonzo-genesis.json && \
    wget -P ${HOME}/node $URL_CONFIG_FILES/testnet-topology.json

# Change config to save them in /root/node/log/node.log file instead of stdout
RUN sed -i 's/StdoutSK/FileSK/' ${HOME}/node/testnet-config.json
RUN sed -i 's/stdout/\/root\/node\/logs\/node.log/' ${HOME}/node/testnet-config.json

# Set node socket for cardano-cli in evironment
ENV CARDANO_NODE_SOCKET_PATH="/root/node/db/node.socket"

# Copy bin folder
COPY bin /root/.local/bin

# Copy scripts
COPY cardano-node-run.sh /root/.local/bin
COPY cardano-cli-*.sh /root/.local/bin/

# Set executable permits
RUN /bin/bash -c "chmod +x /root/.local/bin/cardano-*.sh"

# Set testnet magic number
ENV TESNET_NETWORK_MAGIC=1097911063

# Run cardano-node at the startup
CMD [ "/root/.local/bin/cardano-node-run.sh" ]